### PR TITLE
Nvidia notebook driver

### PR DESCRIPTION
**Pull request by ottnorml**

### CODE REVIEW

**Comment by AeliusSaionji** [comment]
Can you demonstrate that the notebook drivers are different from the desktop drivers? Last I checked, the setups have an identical checksum.

**Comment by ottnorml** [comment]
@AeliusSaionji That's right, at the moment the checksums and so the files are the same. In the future, however, Nvidia could change its publishing behavior and release various files for PC and notebook cards. That's why I thought it would be nice to also have packages for notebooks. :)

**Comment by AeliusSaionji** [comment]
To avoid user confusion and adding unnecessary load on chocolatey's resources, I won't create this until the need arises.

**Comment by akirayamamoto** [comment]
Nvidia now has different installers for desktops and laptops. This PR should proceed.

**Pull request closed without merging**
